# Generated by Django 4.1.9 on 2023-05-19 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webpage',
            options={'ordering': ['-first_published_at'], 'verbose_name': 'Web Page'},
        ),
    ]
