# Generated by Django 4.1.9 on 2023-05-19 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_webpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webpage',
            options={'verbose_name': 'Web Page'},
        ),
    ]
